#!/usr/bin/with-contenv bash
cd /mnt/config/data/server
while grep -q false eula.txt; do
  echo "please accept data/server/eula.txt..."
  sleep 30
done
if ! pgrep -f minedock >/dev/null; then
  s6-setuidgid guardian screen -dmS minedock java -Dlog4j2.formatMsgNoLookups=true ${JAVA_OPTS} -jar server-launcher.jar nogui;
fi
sleep 10
while pgrep -f minedock >/dev/null; do
  sleep 30
done
