---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/minecraft-mcu:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/minecraft-mcu:latest
  - docker tag pdr.nephatrine.net/nephatrine/minecraft-mcu:latest nephatrine/minecraft-mcu:latest
  - HOME=/mnt/config/home docker push nephatrine/minecraft-mcu:latest
  - docker rmi pdr.nephatrine.net/nephatrine/minecraft-mcu:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-minecraft-id
    webhook_token:
      from_secret: wh-minecraft-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: de523a0f816def70d9b83189674f2fcf596148ff6ecf24cd781c7bdbeb13c80d

...
