---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  environment:
    PDR_USER:
      from_secret: docker-user-pdr
    PDR_PASS:
      from_secret: docker-pass-pdr
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/minecraft-mcu:latest .
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker push pdr.nephatrine.net/nephatrine/minecraft-mcu:latest
  - docker logout pdr.nephatrine.net
- name: publish
  environment:
    DOCKER_USER:
      from_secret: docker-user
    DOCKER_PASS:
      from_secret: docker-pass
  commands:
  - docker tag pdr.nephatrine.net/nephatrine/minecraft-mcu:latest nephatrine/minecraft-mcu:latest
  - docker login -p "$DOCKER_PASS" -u "$DOCKER_USER"
  - docker push -a nephatrine/minecraft-mcu
  - docker logout
  depends_on:
  - build

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-minecraft-id
    webhook_token:
      from_secret: wh-minecraft-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 5c71f54a0f860d64178b2ceb778639b4f26f612e2785b8c87b373cb487da9ee2

...
